<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search_ellie-icon-search</name>
   <tag></tag>
   <elementGuidId>ee8429e7-e9dd-4164-ba65-aa08cad16e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ellie-icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='search-2']/form/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2e6a91d3-e4cc-454d-ad0e-1083db76c28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellie-icon-search</value>
      <webElementGuid>3064c23e-a4f0-47c7-a00d-6f8962c9b775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-2&quot;)/form[@class=&quot;search-form&quot;]/button[@class=&quot;search-submit&quot;]/i[@class=&quot;ellie-icon-search&quot;]</value>
      <webElementGuid>a22b1747-25e8-4a03-b026-fbb19be68a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='search-2']/form/button/i</value>
      <webElementGuid>55386d75-85e7-4766-9ee9-e45ba1f1481c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>b71cb997-7117-4d21-8c7f-712d0ee609b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
