<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Flying Ninja_post-thumbnail</name>
   <tag></tag>
   <elementGuidId>5e36ad6d-9b35-4a8f-bab5-dd8c01ac254f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.post-thumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ad6bb46-8d2b-4056-acd9-dc26e2a73345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>post-thumbnail</value>
      <webElementGuid>02d9c59c-5418-4c7e-a65d-1e3f4abace31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/product/flying-ninja/</value>
      <webElementGuid>4cff82b4-472d-4303-86a6-657e1dc88e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2914fec8-e4d8-4f1b-940e-e1b2fa8757de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-54&quot;)/a[@class=&quot;post-thumbnail&quot;]</value>
      <webElementGuid>a4e36890-cdef-4dd0-9f95-9108bdbe3d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-54']/a</value>
      <webElementGuid>a7f49832-3aad-4b27-a1ca-cae5db86379d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flying Ninja'])[2]/following::a[1]</value>
      <webElementGuid>a7442641-26cd-464f-a99f-870a613edfe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flying Ninja'])[1]/following::a[2]</value>
      <webElementGuid>179bb820-f2cd-44d0-87f0-e8ca7b7cba3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on Flying Ninja'])[1]/preceding::a[1]</value>
      <webElementGuid>92cb0f1d-8f51-4026-a869-085146d0a48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://cms.demo.katalon.com/product/flying-ninja/')])[2]</value>
      <webElementGuid>131fadad-5ee4-4146-b20e-f54c3a440a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/a</value>
      <webElementGuid>742afe56-9078-46ed-905d-ab0fd7df9c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cms.demo.katalon.com/product/flying-ninja/']</value>
      <webElementGuid>34be3dc8-8975-4052-85cb-0a6b40a17eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
